services:
  - type: web
    name: doctorwapp
    env: node
    buildCommand: npm install && npm run prisma:generate
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: doctorwapp-db
          property: connectionString
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true 